# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Easy We Chat
subtitle:
description:
author: overtrue
language: zh-cn
timezone: PRC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://easywechat.org
root: /

permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: easywechat

swiftype_key: URYXMYgtQuEhNHNY8d-F
google_analytics: UA-64156348-1
github: overtrue/wechat
twitter: anzhengchao
weibo: 44294631