title: Jan Huang
subtitle: "Developer & Bboy."
description: "I am just a developer."
author: Jan Huang
language: zh-cn
timezone: PRC
url: https://www.janhuang.me
root: /
permalink: blogs/:title.html
archive_dir: blogs
code_dir: downloads/code
new_post_name: :year/:i_month/:i_day/:title/index.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: janhuang
deploy:
  type: git
  repo: git@github.com:JanHuang/janhuang.github.io.git

disqus_shortname: 
google_analytics:
baidu_analytics: 05d3cdd8f4d38f1a7779f39b57cc4d34
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
  zh-tw:
    api_key: c83d2ec3440f40aec6d0e695ecec7ef3
    index_name: hexo_zh-tw
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn
# twitter: 
github: janhuang/site
